import * as ImagePicker from 'expo-image-picker';
import { Stack, useLocalSearchParams } from 'expo-router';
import { useEffect, useMemo, useRef, useState } from 'react';
import {
  Alert,
  Image,
  KeyboardAvoidingView,
  Platform,
  Pressable,
  ScrollView,
  StyleSheet,
  Text,
  TextInput,
  View,
  type ImageStyle,
  type TextStyle,
  type ViewStyle,
} from 'react-native';

import { ErrorState } from '@/components/ErrorState';
import { HairlineRule } from '@/components/HairlineRule';
import { LoadingSkeleton } from '@/components/LoadingSkeleton';
import { SignalMark } from '@/components/SignalMark';
import { useAuth } from '@/lib/auth';
import { type BrandPalette, useBrandPalette, withAlpha } from '@/lib/brandTheme';
import { isDevPreviewAvailable, useDevPreview } from '@/lib/devPreview';
import { appendSignalTurn, createSignalConversation, fetchSignalConversationWithMessages } from '@/lib/db/signal';
import { AppIcon } from '@/lib/icons';
import { usePremium } from '@/lib/premium';
import { PAYWALL_RESULT, presentPremiumPaywall } from '@/lib/purchases';
import { buildSignalContext, buildConversationTitle, getSuggestedPrompts } from '@/lib/signalContext';
import { sendSignalMessage, type SignalChatTurn, type SignalImageAttachment, type SignalUnavailableReason } from '@/lib/signal';
import { exceedsSignalImageSizeLimit, resolveSignalImageMediaType } from '@/lib/signalImageGuard';
import { shouldAutoSubmitInitialPrompt } from '@/lib/signalInitialPrompt';
import { formatSignalUsageLabel } from '@/lib/signalUsage';
import { useAthleteRaces } from '@/lib/racesContext';
import { minTouchSize, spacing } from '@/lib/theme';

interface ChatMessage {
  id: string;
  role: 'user' | 'assistant';
  text: string;
  hadImage?: boolean;
}

interface StagedImage {
  base64: string;
  previewUri: string;
  mediaType: SignalImageAttachment['mediaType'];
}

const THINKING_STATUSES = ['Reading your race history…', 'Analyzing splits…', 'Thinking…'];

// Developer Preview's seeded transcript — hardcoded, never generated by the real Signal edge
// function (see lib/signal.ts's sendSignalMessage, never called from this file while
// isPreviewMode is true). Every figure cited below is a real value from the previewRaces fixture
// (src/fixtures/previewRaces.ts), so the sample reads as a genuine analysis rather than placeholder
// text — it's labeled "Sample analysis" (see the assistantLabel render below) precisely because it
// is one, not a live one.
const PREVIEW_SAMPLE_QUESTION = 'What does my history suggest for my next race?';
const PREVIEW_SAMPLE_ANALYSIS = [
  'Your Olympic-distance form has been trending in the right direction: 2:30:43 at the Niagara Falls Barrelman (Sep 2025), labeled a PR, and 2:30:59 at Wasaga Beach three weeks earlier are your two fastest results at that distance, and the Niagara Falls run split (41:27, 4:08/km) is your fastest off-the-bike 10K-equivalent this season.',
  'At 70.3, your most recent finish, IRONMAN 70.3 Eagleman in 4:54:58, is your fastest half-iron result on record, built on a 36.4 km/h bike average and a 4:39/km run that held up rather than fading. That combination is the strongest signal in your history: a bike that no longer costs you the run.',
  'IRONMAN 70.3 Muskoka is a similar profile to Eagleman, so the realistic target is another PR if you can repeat that bike-to-run transition. Your swim has been the most stable leg across every distance (roughly 37-40 minutes at 70.3), so the run is still where the next real gain is available.',
].join('\n\n');
const PREVIEW_FOLLOWUP_REPLY = "Live analysis isn't available in Developer Preview. This is a static sample.";

/**
 * Splits an assistant reply into paragraphs on a blank line (the conventional delimiter for
 * multi-paragraph plain text — the system prompt forbids markdown, so there's never real
 * heading/list syntax to parse). Presentation-only: the stored message text itself is always one
 * plain string (see ChatMessage / sendSignalMessage) — this never touches how it's produced or
 * persisted, only how it's laid out on screen. The first paragraph gets a slightly larger,
 * medium-bold "lede" treatment (see messageLede); the rest render as standard, generously
 * line-spaced body text (see messageTextAssistant) — see the render below.
 */
function splitParagraphs(text: string): string[] {
  return text
    .split(/\n{2,}/)
    .map((paragraph) => paragraph.trim())
    .filter((paragraph) => paragraph.length > 0);
}

const REASON_MESSAGES: Record<SignalUnavailableReason, string> = {
  unauthorized: 'Please sign in again to use Signal.',
  // Never actually shown — 'rate_limited' is handled specially in sendMessage (paywall for a free
  // athlete, a plain "used up this month" note for premium) before this lookup is ever reached.
  // Kept populated only because REASON_MESSAGES must cover every SignalUnavailableReason.
  rate_limited: "You've used all your Signal asks for this month.",
  bad_request: "Signal couldn't understand that. Please try again.",
  forbidden: "Signal couldn't access that race.",
  model_error: "Signal couldn't respond just now. Please try again.",
  network_error: 'Network issue reaching Signal. Please try again.',
  service_unavailable: "Signal couldn't check your subscription status just now. Please try again.",
};

/**
 * Signal's chat screen (Step 5, V1) — the one real implementation reused from every entry point:
 * seeded from completed Result Detail, seeded from an upcoming Race Detail, unseeded from the
 * Signal tab's "Ask Signal" CTA, or reopened from the Signal tab's "Recent Signals" list (see
 * (tabs)/ask.tsx). A conversation is persisted lazily — only once its first exchange succeeds
 * (see sendMessage) — so an opened-but-abandoned chat never shows up in "Recent Signals".
 */
export default function SignalScreen() {
  const {
    raceId,
    conversationId: conversationIdParam,
    initialPrompt,
  } = useLocalSearchParams<{ raceId?: string; conversationId?: string; initialPrompt?: string }>();
  const races = useAthleteRaces();
  const { session } = useAuth();
  const { mode: devPreviewMode } = useDevPreview();
  // Gates every real-network branch below (seeding, sending, persistence) — see lib/devPreview.tsx.
  // `isDevPreviewAvailable()` is redundant with `devPreviewMode === 'browse'` in practice (that mode
  // is itself only reachable through an available entry point), but kept explicit here so this
  // screen's own safety check never depends solely on _layout.tsx's wiring.
  const isPreviewMode = isDevPreviewAvailable() && devPreviewMode === 'browse';
  const palette = useBrandPalette();
  const styles = useMemo(() => createStyles(palette), [palette]);

  const [messages, setMessages] = useState<ChatMessage[]>(() =>
    isPreviewMode
      ? [
          { id: 'preview-sample-user', role: 'user', text: PREVIEW_SAMPLE_QUESTION },
          { id: 'preview-sample-assistant', role: 'assistant', text: PREVIEW_SAMPLE_ANALYSIS },
        ]
      : [],
  );
  const [inputText, setInputText] = useState('');
  const [stagedImage, setStagedImage] = useState<StagedImage | null>(null);
  const [isSending, setIsSending] = useState(false);
  const [thinkingStatus, setThinkingStatus] = useState(THINKING_STATUSES[0]);
  const [errorText, setErrorText] = useState<string | null>(null);
  // Set from the signal Edge Function's own response after each successful reply (never computed
  // or trusted client-side — see lib/signalUsage.ts). Null until the first reply of this screen
  // instance, so nothing renders before there's a real server-confirmed count to show.
  const [usageState, setUsageState] = useState<{ remaining: number; cap: number; isPremium: boolean } | null>(null);
  const [isUpgrading, setIsUpgrading] = useState(false);
  const { isPremium, refresh: refreshPremiumStatus } = usePremium();
  const scrollRef = useRef<ScrollView>(null);
  // A synchronous, ref-based single-flight guard — `isSending` state alone isn't enough, since a
  // rapid double-invocation (e.g. two near-simultaneous events) can both read the pre-update value
  // before either re-render commits. Checked and set at the very top of sendMessage, before any
  // await, so no event/path (button, suggestion chip, or anything else) can start a second request
  // while one is already in flight.
  const isSendingRef = useRef(false);
  // A suggestion tapped on the Signal landing screen ((tabs)/ask.tsx) arrives here as
  // `initialPrompt` and must be submitted exactly once — never re-submitted on a re-render, and
  // never confused with the reopened-conversation path (`conversationIdParam`, mutually exclusive
  // with this by construction — ask.tsx never sends both). This ref (not just the `initialPrompt`
  // param itself) is what guarantees "exactly once": the effect below still only ever runs a single
  // time per mount regardless of how many times this component re-renders afterward.
  const hasAutoSubmittedInitialPromptRef = useRef(false);

  // Set once a conversation exists in storage — either restored from `conversationIdParam` (a
  // reopened conversation) or created lazily on the first successful exchange of a new one.
  const [conversationId, setConversationId] = useState<string | undefined>(conversationIdParam);
  // The seed race actually driving context assembly: the route param for a fresh conversation, or
  // the conversation's own stored `seed_race_id` once a reopened one finishes loading — never both.
  const [effectiveSeedRaceId, setEffectiveSeedRaceId] = useState<string | undefined>(raceId);
  const [isLoadingConversation, setIsLoadingConversation] = useState(!isPreviewMode && !!conversationIdParam);

  const seedRace = effectiveSeedRaceId ? races.data.find((race) => race.id === effectiveSeedRaceId) : undefined;
  const suggestions = getSuggestedPrompts(races.data, effectiveSeedRaceId);
  // Only the first analysis in a thread gets the "Analysis" kicker — repeating it above every
  // reply would read as chrome, not as a report; later replies are still clearly set apart by the
  // extra spacing/rule around each assistant block (see messageBlockAssistant).
  const firstAssistantMessageId = messages.find((message) => message.role === 'assistant')?.id;

  useEffect(() => {
    // Developer Preview never persists a conversation, so there's nothing to fetch — and this must
    // never call fetchSignalConversationWithMessages (lib/db/signal.ts), the one Supabase read this
    // screen would otherwise make regardless of session state.
    if (isPreviewMode) return;
    if (!conversationIdParam) return;
    let cancelled = false;
    (async () => {
      const result = await fetchSignalConversationWithMessages(conversationIdParam);
      if (cancelled) return;
      if (result) {
        setEffectiveSeedRaceId(result.conversation.seed_race_id ?? undefined);
        setMessages(result.messages.map((message) => ({ id: message.id, role: message.role, text: message.text })));
      }
      setIsLoadingConversation(false);
    })();
    return () => {
      cancelled = true;
    };
  }, [conversationIdParam, isPreviewMode]);

  // Submits a suggestion tapped on the Signal landing screen exactly once, through the exact same
  // sendMessage path a manually-typed question uses (same conversation persistence, same Developer
  // Preview short-circuit) — see (tabs)/ask.tsx's openSignalWithPrompt. Runs once per mount only
  // (guarded by the ref above); a fresh tap of a suggestion always pushes a fresh screen instance,
  // so this never blocks a genuinely new selection, only a duplicate fire within the same instance.
  useEffect(() => {
    if (!shouldAutoSubmitInitialPrompt({ initialPrompt, conversationIdParam, alreadySubmitted: hasAutoSubmittedInitialPromptRef.current })) {
      return;
    }
    hasAutoSubmittedInitialPromptRef.current = true;
    void sendMessage(initialPrompt!);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  useEffect(() => {
    if (!isSending) return;
    let index = 0;
    const interval = setInterval(() => {
      index = (index + 1) % THINKING_STATUSES.length;
      setThinkingStatus(THINKING_STATUSES[index]!);
    }, 2200);
    return () => clearInterval(interval);
  }, [isSending]);

  async function pickImage() {
    const permission = await ImagePicker.requestMediaLibraryPermissionsAsync();
    if (!permission.granted) {
      Alert.alert('Photo access needed', 'Allow RaceSignal to access your photos to attach a screenshot.');
      return;
    }

    const result = await ImagePicker.launchImageLibraryAsync({
      mediaTypes: ImagePicker.MediaTypeOptions.Images,
      base64: true,
      quality: 0.6,
      exif: false,
      allowsEditing: false,
    });
    if (result.canceled) return;

    const asset = result.assets[0];
    if (!asset?.base64) return;

    if (exceedsSignalImageSizeLimit(asset.base64.length)) {
      Alert.alert('Image too large', 'Please choose a smaller screenshot (or crop it) and try again.');
      return;
    }

    setStagedImage({ base64: asset.base64, previewUri: asset.uri, mediaType: resolveSignalImageMediaType(asset) });
    if (inputText.trim().length === 0) {
      setInputText('Analyze this screenshot');
    }
  }

  async function sendMessage(text: string) {
    const trimmed = text.trim();
    if (!trimmed) return;
    if (isSendingRef.current) return; // hard guard — see isSendingRef's comment above.
    isSendingRef.current = true;
    setIsSending(true);

    const image = stagedImage;
    setErrorText(null);
    setMessages((current) => [...current, { id: `${Date.now()}-user`, role: 'user', text: trimmed, hadImage: !!image }]);
    setInputText('');
    setStagedImage(null);
    setThinkingStatus(THINKING_STATUSES[0]!);

    if (isPreviewMode) {
      // Never calls sendSignalMessage (lib/signal.ts) or appendSignalTurn/createSignalConversation
      // (lib/db/signal.ts) — a canned, clearly-labeled reply instead, so a tester who types into the
      // preview chat gets an honest response rather than a silent no-op or a real network call.
      setMessages((current) => [...current, { id: `${Date.now()}-assistant`, role: 'assistant', text: PREVIEW_FOLLOWUP_REPLY }]);
      isSendingRef.current = false;
      setIsSending(false);
      return;
    }

    try {
      const context = buildSignalContext(races.data, effectiveSeedRaceId);
      const history: SignalChatTurn[] = messages.map((message) => ({ role: message.role, text: message.text }));

      const result = await sendSignalMessage(
        context,
        history,
        trimmed,
        image ? { base64: image.base64, mediaType: image.mediaType } : undefined,
      );

      if (!result.available) {
        // `result.detail` (a safe, truncated backend diagnostic — see lib/signal.ts) is
        // deliberately not shown here: it was useful while chasing real device failures, but an
        // athlete-facing error should stay short and friendly, never expose implementation
        // details. It's still logged via console.warn in sendSignalMessage for developer use.
        if (result.reason === 'rate_limited' && !isPremium) {
          // A free athlete who's exhausted their monthly allowance sees the RevenueCat paywall
          // itself, not a generic error (Step 8.5) — presentPremiumPaywall's own "×" close button
          // is what makes this dismissible. isPremium here only decides WHICH message/paywall the
          // UI shows after the server has already said no; the allowance itself is enforced
          // entirely server-side (see supabase/functions/signal/index.ts) regardless of this flag.
          const paywallResult = await presentPremiumPaywall();
          if (paywallResult === PAYWALL_RESULT.PURCHASED || paywallResult === PAYWALL_RESULT.RESTORED) {
            await refreshPremiumStatus();
            // Drop the just-added user turn so retrying doesn't duplicate it — sendMessage always
            // re-appends it fresh.
            setMessages((current) => current.slice(0, -1));
            isSendingRef.current = false;
            setIsSending(false);
            await sendMessage(trimmed);
            return;
          }
          setErrorText(
            "You've used your free Signal asks for this month. Upgrade to RaceSignal Premium any time to keep asking.",
          );
          return;
        }
        if (result.reason === 'rate_limited') {
          // Already premium and still hit the (40/month) cap — no paywall to offer.
          setErrorText("You've used all your Signal asks for this month. More become available next month.");
          return;
        }
        setErrorText(REASON_MESSAGES[result.reason]);
        return;
      }
      setMessages((current) => [...current, { id: `${Date.now()}-assistant`, role: 'assistant', text: result.data.reply }]);
      setUsageState({ remaining: result.data.remaining, cap: result.data.cap, isPremium: result.data.isPremium });

      // Persist this turn — lazily creates the conversation on the first successful exchange, so
      // an abandoned chat with no real reply never shows up in "Recent Signals". A failure here is
      // soft: the conversation itself already succeeded, only the save didn't, so it's logged, not
      // surfaced as a chat error.
      const athleteId = session?.user.id;
      if (athleteId) {
        try {
          let activeConversationId = conversationId;
          if (!activeConversationId) {
            const title = buildConversationTitle(seedRace, trimmed);
            const created = await createSignalConversation(athleteId, title, effectiveSeedRaceId);
            activeConversationId = created.id;
            setConversationId(created.id);
          }
          await appendSignalTurn(activeConversationId, trimmed, result.data.reply);
        } catch (err) {
          console.warn('[Signal] failed to persist conversation turn:', err);
        }
      }
    } finally {
      isSendingRef.current = false;
      setIsSending(false);
    }
  }

  // The compact usage strip's "Upgrade" action (Build 10 polish) — a plain upsell entry point, not
  // the exhausted-allowance paywall path above (which is triggered by a real rate_limited
  // response). Presents the same RevenueCat-hosted paywall either way.
  async function handleUpgradePress() {
    if (isUpgrading) return;
    setIsUpgrading(true);
    await presentPremiumPaywall();
    await refreshPremiumStatus();
    setIsUpgrading(false);
  }

  const headerTitle = seedRace ? seedRace.name : 'Ask Signal';

  return (
    <KeyboardAvoidingView
      style={styles.flex}
      behavior={Platform.OS === 'ios' ? 'padding' : undefined}
      keyboardVerticalOffset={90}>
      <Stack.Screen options={{ title: headerTitle }} />
      <View style={styles.screen}>
        {races.isLoading || isLoadingConversation ? (
          <LoadingSkeleton rows={4} />
        ) : races.isError ? (
          <ErrorState />
        ) : (
          <ScrollView
            ref={scrollRef}
            contentContainerStyle={styles.content}
            contentInsetAdjustmentBehavior="automatic"
            onContentSizeChange={() => scrollRef.current?.scrollToEnd({ animated: true })}>
            {seedRace ? (
              <Text style={styles.seedNote}>
                Signal has your {seedRace.name} result and your full race history.
              </Text>
            ) : (
              <Text style={styles.seedNote}>Signal has your full race history.</Text>
            )}

            {messages.length > 0 ? (
              <View style={styles.messages}>
                {messages.map((message) => (
                  <View
                    key={message.id}
                    style={[
                      styles.messageBlock,
                      // Extra separation ahead of each analysis reply — the athlete's question above
                      // it stays visually distinct rather than the reply reading as a quick follow-up.
                      message.role === 'assistant' ? styles.messageBlockAssistant : null,
                    ]}>
                    <View style={message.role === 'user' ? styles.messageUser : styles.messageAssistant}>
                      {message.role === 'assistant' && message.id === firstAssistantMessageId ? (
                        <View style={styles.assistantLabelRow}>
                          <SignalMark color={palette.inkSecondary} size={11} />
                          <Text style={styles.assistantLabel}>
                            {isPreviewMode ? 'Sample analysis (Developer Preview)' : 'Analysis'}
                          </Text>
                        </View>
                      ) : null}
                      {message.hadImage ? (
                        <View style={styles.imageTagRow}>
                          <AppIcon name="camera-outline" size={13} color={palette.inkSecondary} />
                          <Text style={styles.imageTag}>Screenshot attached</Text>
                        </View>
                      ) : null}
                      {message.role === 'user' ? (
                        // The athlete's own question — a distinct, headline-like line of context
                        // (ink-colored, left-aligned, medium-bold), not a right-aligned chat bubble
                        // utterance — so it reads as "here's what was asked" before the analysis.
                        <Text style={styles.messageTextUser}>{message.text}</Text>
                      ) : (
                        // The analysis reply, split into paragraphs on a blank line. The first
                        // paragraph gets a slightly larger, medium-bold editorial "lede" treatment;
                        // the rest are standard, generously line-spaced body text. Spacing between
                        // paragraphs comes entirely from `assistantParagraphs`' own gap — no
                        // hairlines or manufactured section headings between them, only real
                        // paragraph breaks in the (unaltered) reply text itself.
                        <View style={styles.assistantParagraphs}>
                          {splitParagraphs(message.text).map((paragraph, index) => (
                            <Text key={index} style={index === 0 ? styles.messageLede : styles.messageTextAssistant}>
                              {paragraph}
                            </Text>
                          ))}
                        </View>
                      )}
                    </View>
                    <HairlineRule color={palette.hairline} />
                  </View>
                ))}
                {isSending ? (
                  <View style={styles.thinkingRow}>
                    <SignalMark color={palette.inkSecondary} size={12} />
                    <Text style={styles.thinkingText}>{thinkingStatus}</Text>
                  </View>
                ) : null}
              </View>
            ) : null}

            {messages.length === 0 && !isSending ? (
              <View style={styles.suggestionRow}>
                <HairlineRule color={palette.hairline} />
                {suggestions.map((suggestion, index) => (
                  <View key={suggestion}>
                    <Pressable
                      onPress={() => sendMessage(suggestion)}
                      accessibilityRole="button"
                      accessibilityLabel={suggestion}
                      style={styles.suggestionChip}>
                      <Text style={styles.suggestionLabel}>{suggestion}</Text>
                      <AppIcon name="chevron-right" size={17} color={palette.inkSecondary} />
                    </Pressable>
                    {index < suggestions.length - 1 ? <HairlineRule color={palette.hairline} /> : null}
                  </View>
                ))}
              </View>
            ) : null}

            {errorText ? <Text style={styles.errorText}>{errorText}</Text> : null}
          </ScrollView>
        )}

        {stagedImage ? (
          <View style={styles.stagedImageRow}>
            <Image source={{ uri: stagedImage.previewUri }} style={styles.stagedImageThumb} />
            <Text style={styles.stagedImageLabel}>Screenshot ready to send</Text>
            <Pressable
              onPress={() => setStagedImage(null)}
              accessibilityRole="button"
              accessibilityLabel="Remove screenshot"
              hitSlop={8}
              style={styles.stagedImageRemove}>
              <AppIcon name="close" size={16} color={palette.inkSecondary} />
            </Pressable>
          </View>
        ) : null}

        {/* Compact Signal-blue usage strip (Build 10 polish) — restrained by design: same
            treatment for free and premium, no large banner, no upgrade CTA once premium. */}
        {usageState ? (
          <View style={styles.usageStrip}>
            <Text style={styles.usageStripText}>
              {formatSignalUsageLabel(usageState.remaining, usageState.cap, usageState.isPremium)}
            </Text>
            {!usageState.isPremium ? (
              <Pressable onPress={handleUpgradePress} disabled={isUpgrading} accessibilityRole="button" accessibilityLabel="Upgrade">
                <Text style={styles.usageStripUpgrade}>{isUpgrading ? '…' : 'Upgrade'}</Text>
              </Pressable>
            ) : null}
          </View>
        ) : null}

        <View style={styles.inputBar}>
          <Pressable
            onPress={pickImage}
            accessibilityRole="button"
            accessibilityLabel="Attach a screenshot"
            style={styles.attachButton}>
            <AppIcon name="camera-outline" size={22} color={palette.signalBlue} />
          </Pressable>
          <TextInput
            value={inputText}
            onChangeText={setInputText}
            placeholder="Ask Signal about your races…"
            placeholderTextColor={palette.inkSecondary}
            style={styles.input}
            accessibilityLabel="Message"
            multiline
            // The send button is the ONLY send action (V1 device-test requirement) — keyboard
            // Return must only ever insert a newline. blurOnSubmit={false} keeps the keyboard from
            // dismissing on Return (the multiline default, made explicit here rather than relied
            // on), returnKeyType="default" keeps the key labeled/behaving like a plain return
            // rather than a "Send"/"Go" key, and onSubmitEditing is an explicit no-op so no future
            // change can accidentally wire Return to sendMessage.
            blurOnSubmit={false}
            returnKeyType="default"
            onSubmitEditing={() => {}}
          />
          <Pressable
            onPress={() => sendMessage(inputText)}
            disabled={inputText.trim().length === 0 || isSending}
            accessibilityRole="button"
            accessibilityLabel="Send"
            style={[styles.sendButton, (inputText.trim().length === 0 || isSending) && styles.sendButtonDisabled]}>
            <AppIcon name="arrow-up" size={20} color={palette.onSignalBlue} />
          </Pressable>
        </View>
      </View>
    </KeyboardAvoidingView>
  );
}

interface Styles {
  flex: ViewStyle;
  screen: ViewStyle;
  content: ViewStyle;
  seedNote: TextStyle;
  messages: ViewStyle;
  messageBlock: ViewStyle;
  messageBlockAssistant: ViewStyle;
  messageUser: ViewStyle;
  messageAssistant: ViewStyle;
  assistantLabelRow: ViewStyle;
  assistantLabel: TextStyle;
  messageTextUser: TextStyle;
  assistantParagraphs: ViewStyle;
  messageLede: TextStyle;
  messageTextAssistant: TextStyle;
  imageTagRow: ViewStyle;
  imageTag: TextStyle;
  thinkingRow: ViewStyle;
  thinkingText: TextStyle;
  suggestionRow: ViewStyle;
  suggestionChip: ViewStyle;
  suggestionLabel: TextStyle;
  errorText: TextStyle;
  usageStrip: ViewStyle;
  usageStripText: TextStyle;
  usageStripUpgrade: TextStyle;
  stagedImageRow: ViewStyle;
  stagedImageThumb: ImageStyle;
  stagedImageLabel: TextStyle;
  stagedImageRemove: ViewStyle;
  inputBar: ViewStyle;
  attachButton: ViewStyle;
  input: TextStyle;
  sendButton: ViewStyle;
  sendButtonDisabled: ViewStyle;
}

function createStyles(palette: BrandPalette): Styles {
  return StyleSheet.create({
    flex: {
      flex: 1,
    },
    screen: {
      flex: 1,
      backgroundColor: palette.canvas,
    },
    content: {
      padding: spacing.lg,
      gap: spacing.md,
    },
    seedNote: {
      fontSize: 13,
      color: palette.inkSecondary,
    },
    messages: {
      gap: spacing.md,
    },
    messageBlock: {
      gap: spacing.sm,
    },
    // Generous separation between the athlete's question and Signal's reply — pulled apart well
    // beyond the default rhythm between turns, so the reply reads as a distinct, considered piece
    // of writing (a report beginning) rather than the next line of a quick back-and-forth.
    messageBlockAssistant: {
      marginTop: spacing.lg,
    },
    // Left-aligned like everything else on the screen — a clear line of context/heading to read
    // before the analysis, not a right-aligned chat-bubble utterance.
    messageUser: {
      alignItems: 'flex-start',
      gap: 4,
    },
    messageAssistant: {
      alignItems: 'flex-start',
      gap: 10,
    },
    assistantLabelRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    // Kicker-style label above the first analysis in a thread — small caps, letter-spaced, quiet
    // ink-secondary — reads as a report heading rather than repeated chat chrome.
    assistantLabel: {
      fontSize: 11,
      fontWeight: '700',
      letterSpacing: 1,
      textTransform: 'uppercase',
      color: palette.inkSecondary,
    },
    // The question itself, read distinctly — ink-colored and a touch heavier than plain body text,
    // like a clear line of context/context heading rather than a dimmed chat utterance.
    messageTextUser: {
      fontSize: 16,
      fontWeight: '600',
      lineHeight: 22,
      color: palette.ink,
    },
    // Strong spacing between paragraphs (not just one line-height applied to the whole reply) —
    // this is the entire source of the reply's visual hierarchy, alongside `messageLede` below.
    assistantParagraphs: {
      gap: spacing.lg,
    },
    // The reply's first paragraph only — a slightly larger, medium-bold editorial "lede" so the
    // analysis opens with a moment of emphasis, the way a coach's note or a short report would,
    // never a manufactured heading (the paragraph is real reply text, just weighted differently).
    messageLede: {
      fontSize: 17,
      fontWeight: '600',
      lineHeight: 25,
      color: palette.ink,
    },
    // Every paragraph after the lede — generous line-height so an analysis reads as a considered
    // piece of writing, not a quick chat bubble.
    messageTextAssistant: {
      fontSize: 15,
      lineHeight: 24,
      color: palette.ink,
    },
    imageTagRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
    },
    imageTag: {
      fontSize: 12,
      color: palette.inkSecondary,
    },
    thinkingRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingVertical: spacing.xs,
    },
    thinkingText: {
      fontSize: 13,
      fontStyle: 'italic',
      color: palette.inkSecondary,
    },
    suggestionRow: {
      gap: 0,
    },
    // Editorial row, not a pill — matches the Signal tab landing screen's "Things worth asking"
    // treatment: question text, subtle chevron, hairline separators between rows.
    suggestionChip: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: spacing.sm,
      minHeight: 44,
      paddingVertical: spacing.sm,
    },
    suggestionLabel: {
      flex: 1,
      fontSize: 14,
      fontWeight: '500',
      color: palette.ink,
    },
    errorText: {
      fontSize: 13,
      color: palette.danger,
    },
    usageStrip: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginHorizontal: spacing.lg,
      marginBottom: spacing.xs,
      paddingHorizontal: spacing.md,
      paddingVertical: spacing.xs,
      borderRadius: 10,
      backgroundColor: withAlpha(palette.signalBlue, 0.08),
    },
    usageStripText: {
      fontSize: 12,
      fontWeight: '600',
      color: palette.signalBlue,
    },
    usageStripUpgrade: {
      fontSize: 12,
      fontWeight: '700',
      color: palette.signalBlue,
      textDecorationLine: 'underline',
    },
    stagedImageRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.sm,
      paddingHorizontal: spacing.md,
      paddingTop: spacing.sm,
      backgroundColor: palette.canvas,
    },
    stagedImageThumb: {
      width: 36,
      height: 36,
      borderRadius: 8,
    },
    stagedImageLabel: {
      fontSize: 13,
      color: palette.inkSecondary,
      flex: 1,
    },
    stagedImageRemove: {
      minWidth: 32,
      minHeight: 32,
      alignItems: 'center',
      justifyContent: 'center',
    },
    inputBar: {
      flexDirection: 'row',
      alignItems: 'flex-end',
      gap: spacing.sm,
      padding: spacing.md,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: palette.hairline,
      backgroundColor: palette.canvas,
    },
    attachButton: {
      minWidth: minTouchSize,
      minHeight: minTouchSize,
      alignItems: 'center',
      justifyContent: 'center',
    },
    input: {
      flex: 1,
      minHeight: minTouchSize,
      maxHeight: 100,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: palette.hairline,
      borderRadius: 20,
      paddingHorizontal: spacing.md,
      paddingVertical: spacing.sm,
      color: palette.ink,
    },
    sendButton: {
      width: minTouchSize,
      height: minTouchSize,
      borderRadius: minTouchSize / 2,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: palette.signalBlue,
    },
    sendButtonDisabled: {
      opacity: 0.4,
    },
  });
}
