import * as ImagePicker from 'expo-image-picker';
import Constants from 'expo-constants';
import { Stack, useFocusEffect, useLocalSearchParams } from 'expo-router';
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import {
  Alert,
  AppState,
  Image,
  KeyboardAvoidingView,
  Platform,
  Pressable,
  ScrollView,
  StyleSheet,
  Text,
  TextInput,
  View,
  type ImageStyle,
  type TextStyle,
  type ViewStyle,
} from 'react-native';

import { ErrorState } from '@/components/ErrorState';
import { HairlineRule } from '@/components/HairlineRule';
import { LoadingSkeleton } from '@/components/LoadingSkeleton';
import { SignalAllowance } from '@/components/SignalAllowance';
import { SignalConsentSheet } from '@/components/SignalConsentSheet';
import { SignalMark } from '@/components/SignalMark';
import { useAuth } from '@/lib/auth';
import { type BrandPalette, useBrandPalette, withAlpha } from '@/lib/brandTheme';
import { isDevPreviewAvailable, useDevPreview } from '@/lib/devPreview';
import { appendSignalTurn, createSignalConversation, fetchSignalConversationWithMessages } from '@/lib/db/signal';
import { AppIcon } from '@/lib/icons';
import { usePremium } from '@/lib/premium';
import { presentPremiumPaywall } from '@/lib/purchases';
import { buildSignalContext, buildConversationTitle, getSuggestedPrompts } from '@/lib/signalContext';
import {
  generateSignalRequestId,
  sendSignalMessage,
  type SignalChatTurn,
  type SignalImageAttachment,
  type SignalUnavailableReason,
} from '@/lib/signal';
import { hasAgreedToSignalDisclosure, saveSignalConsent, SIGNAL_CONSENT_DISCLOSURE_VERSION } from '@/lib/signalConsent';
import { exceedsSignalImageSizeLimit, resolveSignalImageMediaType } from '@/lib/signalImageGuard';
import { promptById } from '@/lib/notifications/prompts';
import { appendStarter, loadSignalDraft, planStarter, saveSignalDraft } from '@/lib/signalDraft';
import { shouldAutoSubmitInitialPrompt } from '@/lib/signalInitialPrompt';
import { formatPremiumExhaustedMessage, isFreeExhausted, isPremiumExhausted, PREMIUM_MONTHLY_ASKS } from '@/lib/signalUsage';
import { useInputFocusRequest } from '@/lib/useInputFocusRequest';
import { useSignalUsage } from '@/lib/useSignalUsage';
import { useAthleteRaces } from '@/lib/racesContext';
import { isNearBottom, messageTopGap, QUESTION_BUBBLE_MAX_WIDTH } from '@/lib/signalLayout';
import { minTouchSize, spacing } from '@/lib/theme';

interface ChatMessage {
  id: string;
  role: 'user' | 'assistant';
  text: string;
  hadImage?: boolean;
}

interface StagedImage {
  base64: string;
  previewUri: string;
  mediaType: SignalImageAttachment['mediaType'];
}

const THINKING_STATUSES = ['Reading your race history…', 'Analyzing splits…', 'Thinking…'];

// Developer Preview's seeded transcript — hardcoded, never generated by the real Signal edge
// function (see lib/signal.ts's sendSignalMessage, never called from this file while
// isPreviewMode is true). Every figure cited below is a real value from the previewRaces fixture
// (src/fixtures/previewRaces.ts), so the sample reads as a genuine analysis rather than placeholder
// text — it's labeled "Sample analysis" (see the assistantLabel render below) precisely because it
// is one, not a live one.
const PREVIEW_SAMPLE_QUESTION = 'What does my history suggest for my next race?';
const PREVIEW_SAMPLE_ANALYSIS = [
  'Your Olympic-distance form has been trending in the right direction: 2:30:43 at the Niagara Falls Barrelman (Sep 2025), labeled a PR, and 2:30:59 at Wasaga Beach three weeks earlier are your two fastest results at that distance, and the Niagara Falls run split (41:27, 4:08/km) is your fastest off-the-bike 10K-equivalent this season.',
  'At 70.3, your most recent finish, IRONMAN 70.3 Eagleman in 4:54:58, is your fastest half-iron result on record, built on a 36.4 km/h bike average and a 4:39/km run that held up rather than fading. That combination is the strongest signal in your history: a bike that no longer costs you the run.',
  'IRONMAN 70.3 Muskoka is a similar profile to Eagleman, so the realistic target is another PR if you can repeat that bike-to-run transition. Your swim has been the most stable leg across every distance (roughly 37-40 minutes at 70.3), so the run is still where the next real gain is available.',
].join('\n\n');
const PREVIEW_FOLLOWUP_REPLY = "Live analysis isn't available in Developer Preview. This is a static sample.";

/**
 * Splits an assistant reply into paragraphs on a blank line (the conventional delimiter for
 * multi-paragraph plain text — the system prompt forbids markdown, so there's never real
 * heading/list syntax to parse). Presentation-only: the stored message text itself is always one
 * plain string (see ChatMessage / sendSignalMessage) — this never touches how it's produced or
 * persisted, only how it's laid out on screen. Every paragraph renders in the same answer style.
 */
function splitParagraphs(text: string): string[] {
  return text
    .split(/\n{2,}/)
    .map((paragraph) => paragraph.trim())
    .filter((paragraph) => paragraph.length > 0);
}

const REASON_MESSAGES: Record<SignalUnavailableReason, string> = {
  unauthorized: 'Please sign in again to use Signal.',
  // Never actually shown — 'rate_limited' is handled specially in sendMessage (paywall for a free
  // athlete who's used their 3 lifetime asks, a plain "used up this month" note for premium)
  // before this lookup is ever reached. Kept populated only because REASON_MESSAGES must cover
  // every SignalUnavailableReason; deliberately tier-neutral wording since it's a fallback, not
  // the real free- or premium-specific message.
  rate_limited: "You've used all your available Signal asks.",
  bad_request: "Signal couldn't understand that. Please try again.",
  forbidden: "Signal couldn't access that race.",
  model_error: "Signal couldn't respond just now. Please try again.",
  network_error: 'Network issue reaching Signal. Please try again.',
  service_unavailable: "Signal couldn't check your subscription status just now. Please try again.",
  timeout: "Signal took longer than expected to respond. Please try again.",
  duplicate_in_flight: "Signal is still working on your last question. Please wait a moment and try again.",
};

/**
 * Signal's chat screen (Step 5, V1) — the one real implementation reused from every entry point:
 * seeded from completed Result Detail, seeded from an upcoming Race Detail, unseeded from the
 * Signal tab's "Ask Signal" CTA, or reopened from the Signal tab's "Recent Signals" list (see
 * (tabs)/ask.tsx). A conversation is persisted lazily — only once its first exchange succeeds
 * (see sendMessage) — so an opened-but-abandoned chat never shows up in "Recent Signals".
 */
export default function SignalScreen() {
  const {
    raceId,
    conversationId: conversationIdParam,
    initialPrompt,
    starter,
  } = useLocalSearchParams<{ raceId?: string; conversationId?: string; initialPrompt?: string; starter?: string }>();
  const races = useAthleteRaces();
  const { session } = useAuth();
  const { mode: devPreviewMode } = useDevPreview();
  // Gates every real-network branch below (seeding, sending, persistence) — see lib/devPreview.tsx.
  // `isDevPreviewAvailable()` is redundant with `devPreviewMode === 'browse'` in practice (that mode
  // is itself only reachable through an available entry point), but kept explicit here so this
  // screen's own safety check never depends solely on _layout.tsx's wiring.
  const isPreviewMode = isDevPreviewAvailable() && devPreviewMode === 'browse';
  const palette = useBrandPalette();
  const styles = useMemo(() => createStyles(palette), [palette]);

  const [messages, setMessages] = useState<ChatMessage[]>(() =>
    isPreviewMode
      ? [
          { id: 'preview-sample-user', role: 'user', text: PREVIEW_SAMPLE_QUESTION },
          { id: 'preview-sample-assistant', role: 'assistant', text: PREVIEW_SAMPLE_ANALYSIS },
        ]
      : [],
  );
  const [inputText, setInputText] = useState('');
  // The composer text, kept per athlete so it survives leaving the screen and cold starts (see lib/signalDraft.ts).
  const inputTextRef = useRef('');
  inputTextRef.current = inputText;
  const inputRef = useRef<TextInput>(null);
  const [draftLoaded, setDraftLoaded] = useState(false);
  // A between-race notification's suggested starter that was NOT applied because the athlete already has a draft: offered as an explicit choice.
  const [starterOffer, setStarterOffer] = useState<string | null>(null);
  const starterHandledRef = useRef(false);
  // Whether this screen is the focused one (focus after a navigation must wait for it), and a reliable focus request for the composer.
  const [screenFocused, setScreenFocused] = useState(false);
  useFocusEffect(
    useCallback(() => {
      setScreenFocused(true);
      return () => setScreenFocused(false);
    }, []),
  );
  const { requestFocus, status: focusStatus } = useInputFocusRequest(inputRef, screenFocused);
  const [stagedImage, setStagedImage] = useState<StagedImage | null>(null);
  const [isSending, setIsSending] = useState(false);
  const [thinkingStatus, setThinkingStatus] = useState(THINKING_STATUSES[0]);
  const [errorText, setErrorText] = useState<string | null>(null);
  // Reliability investigation (B.1 Task 1a): a failed/timed-out question must stay recoverable via
  // a clear Retry action, never a dead end that forces retyping. Holds exactly the text/image of the
  // attempt that just failed (never a stale one — cleared at the top of every sendMessage call, see
  // below), so `retryLastMessage` can re-submit that exact attempt without duplicating quota-side
  // bookkeeping the athlete didn't ask for.
  const [lastFailedAttempt, setLastFailedAttempt] = useState<{ text: string; image: StagedImage | null; requestId: string } | null>(
    null,
  );
  // First-use Signal consent (B.12) — sendMessage checks this BEFORE touching inputText/stagedImage
  // or sending anything, so declining leaves the athlete's typed question exactly as they left it.
  // `pendingSignalSend` holds the exact attempt that triggered the gate, so "Agree and continue"
  // resumes it verbatim rather than asking the athlete to retype/re-tap anything.
  const [showConsentSheet, setShowConsentSheet] = useState(false);
  const [pendingSignalSend, setPendingSignalSend] = useState<{ text: string; image: StagedImage | null; requestId?: string } | null>(
    null,
  );
  const [isUpgrading, setIsUpgrading] = useState(false);
  const { isPremium, refresh: refreshPremiumStatus } = usePremium();
  // The allowance, as the server reports it: refreshed when Signal opens or regains focus, after sends settle, and after every
  // paywall return. Null (nothing shown) whenever it is unknown; unknown is never treated as zero or as Premium.
  const { usage, refresh: refreshUsage, applyReply: applyReplyUsage } = useSignalUsage({ enabled: !isPreviewMode && !!session?.user.id });
  // Single-flight guard for the paywall hand-off below, so a send cannot open it twice.
  const paywallInFlightRef = useRef(false);
  const scrollRef = useRef<ScrollView>(null);
  // A synchronous, ref-based single-flight guard — `isSending` state alone isn't enough, since a
  // rapid double-invocation (e.g. two near-simultaneous events) can both read the pre-update value
  // before either re-render commits. Checked and set at the very top of sendMessage, before any
  // await, so no event/path (button, suggestion chip, or anything else) can start a second request
  // while one is already in flight.
  const isSendingRef = useRef(false);
  // A suggestion tapped on the Signal landing screen ((tabs)/ask.tsx) arrives here as
  // `initialPrompt` and must be submitted exactly once — never re-submitted on a re-render, and
  // never confused with the reopened-conversation path (`conversationIdParam`, mutually exclusive
  // with this by construction — ask.tsx never sends both). This ref (not just the `initialPrompt`
  // param itself) is what guarantees "exactly once": the effect below still only ever runs a single
  // time per mount regardless of how many times this component re-renders afterward.
  const hasAutoSubmittedInitialPromptRef = useRef(false);

  // Set once a conversation exists in storage — either restored from `conversationIdParam` (a
  // reopened conversation) or created lazily on the first successful exchange of a new one.
  const [conversationId, setConversationId] = useState<string | undefined>(conversationIdParam);
  // The seed race actually driving context assembly: the route param for a fresh conversation, or
  // the conversation's own stored `seed_race_id` once a reopened one finishes loading — never both.
  const [effectiveSeedRaceId, setEffectiveSeedRaceId] = useState<string | undefined>(raceId);
  const [isLoadingConversation, setIsLoadingConversation] = useState(!isPreviewMode && !!conversationIdParam);

  const seedRace = effectiveSeedRaceId ? races.data.find((race) => race.id === effectiveSeedRaceId) : undefined;
  const suggestions = getSuggestedPrompts(races.data, effectiveSeedRaceId);
  // Whether new content should pull the view to the end: true while the athlete is at (or near) the end, and set again
  // whenever they send a message; false once they scroll up to read earlier messages.
  const followLatestRef = useRef(true);

  useEffect(() => {
    // Developer Preview never persists a conversation, so there's nothing to fetch — and this must
    // never call fetchSignalConversationWithMessages (lib/db/signal.ts), the one Supabase read this
    // screen would otherwise make regardless of session state.
    if (isPreviewMode) return;
    if (!conversationIdParam) return;
    let cancelled = false;
    (async () => {
      const result = await fetchSignalConversationWithMessages(conversationIdParam);
      if (cancelled) return;
      if (result) {
        setEffectiveSeedRaceId(result.conversation.seed_race_id ?? undefined);
        setMessages(result.messages.map((message) => ({ id: message.id, role: message.role, text: message.text })));
      }
      setIsLoadingConversation(false);
    })();
    return () => {
      cancelled = true;
    };
  }, [conversationIdParam, isPreviewMode]);

  // Submits a suggestion tapped on the Signal landing screen exactly once, through the exact same
  // sendMessage path a manually-typed question uses (same conversation persistence, same Developer
  // Preview short-circuit) — see (tabs)/ask.tsx's openSignalWithPrompt. Runs once per mount only
  // (guarded by the ref above); a fresh tap of a suggestion always pushes a fresh screen instance,
  // so this never blocks a genuinely new selection, only a duplicate fire within the same instance.
  useEffect(() => {
    if (!shouldAutoSubmitInitialPrompt({ initialPrompt, conversationIdParam, alreadySubmitted: hasAutoSubmittedInitialPromptRef.current })) {
      return;
    }
    hasAutoSubmittedInitialPromptRef.current = true;
    void sendMessage(initialPrompt!);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // Restore this athlete's saved draft (never over text they have already started typing).
  const draftAthleteId = !isPreviewMode ? session?.user.id : undefined;
  useEffect(() => {
    if (!draftAthleteId) {
      setDraftLoaded(true);
      return;
    }
    let cancelled = false;
    (async () => {
      const saved = await loadSignalDraft(draftAthleteId);
      if (cancelled) return;
      if (saved.trim().length > 0 && inputTextRef.current.trim().length === 0) setInputText(saved);
      setDraftLoaded(true);
    })();
    return () => {
      cancelled = true;
    };
  }, [draftAthleteId]);

  // Save the draft shortly after it changes, and once more when the screen goes away. An empty composer clears the saved draft.
  useEffect(() => {
    if (!draftAthleteId || !draftLoaded) return;
    const timer = setTimeout(() => void saveSignalDraft(draftAthleteId, inputText), 400);
    return () => clearTimeout(timer);
  }, [draftAthleteId, draftLoaded, inputText]);
  useEffect(() => {
    if (!draftAthleteId) return;
    return () => {
      void saveSignalDraft(draftAthleteId, inputTextRef.current);
    };
  }, [draftAthleteId]);

  // A between-race notification opens Signal with a suggested starter. It fills the composer (editable) only when there is NO draft; with an
  // existing draft nothing changes and the starter is offered as an explicit choice. It is never sent, and never uses an ask.
  useEffect(() => {
    if (!starter || !draftLoaded || starterHandledRef.current || isPreviewMode) return;
    const prompt = promptById(starter);
    starterHandledRef.current = true;
    if (!prompt) return;
    const plan = planStarter(inputTextRef.current, prompt.draft);
    if (plan.action === 'use') {
      setInputText(plan.text);
      requestFocus();
    } else {
      setStarterOffer(plan.starter);
    }
  }, [starter, draftLoaded, isPreviewMode, requestFocus]);

  useEffect(() => {
    if (!isSending) return;
    let index = 0;
    const interval = setInterval(() => {
      index = (index + 1) % THINKING_STATUSES.length;
      setThinkingStatus(THINKING_STATUSES[index]!);
    }, 2200);
    return () => clearInterval(interval);
  }, [isSending]);

  async function pickImage() {
    const permission = await ImagePicker.requestMediaLibraryPermissionsAsync();
    if (!permission.granted) {
      Alert.alert('Photo access needed', 'Allow RaceSignal to access your photos to attach a screenshot.');
      return;
    }

    const result = await ImagePicker.launchImageLibraryAsync({
      mediaTypes: ImagePicker.MediaTypeOptions.Images,
      base64: true,
      quality: 0.6,
      exif: false,
      allowsEditing: false,
    });
    if (result.canceled) return;

    const asset = result.assets[0];
    if (!asset?.base64) return;

    if (exceedsSignalImageSizeLimit(asset.base64.length)) {
      Alert.alert('Image too large', 'Please choose a smaller screenshot (or crop it) and try again.');
      return;
    }

    setStagedImage({ base64: asset.base64, previewUri: asset.uri, mediaType: resolveSignalImageMediaType(asset) });
    if (inputText.trim().length === 0) {
      setInputText('Analyze this screenshot');
    }
  }

  /** `skipAllowanceCheck` is only passed by the paywall hand-off, once the server has just confirmed an available allowance. */
  async function sendMessage(text: string, imageOverride?: StagedImage | null, requestIdOverride?: string, skipAllowanceCheck = false) {
    const trimmed = text.trim();
    if (!trimmed) return;
    if (isSendingRef.current) return; // hard guard — see isSendingRef's comment above.

    // `imageOverride`/`requestIdOverride` (only ever passed by retryLastMessage below) re-attach
    // the exact image AND request identity the failed attempt used — by the time of a retry,
    // `stagedImage` state has already been cleared, and the requestId must be the SAME one (never
    // a fresh one) so the server can recognize this as a retry of the same logical question rather
    // than a brand-new one (see lib/signal.ts's generateSignalRequestId).
    const image = imageOverride !== undefined ? imageOverride : stagedImage;
    const requestId = requestIdOverride ?? generateSignalRequestId();

    // A balance the server has confirmed is used up never reaches the transcript or the model: Send is intercepted here, before any
    // message is added or any input cleared, so the draft and any attachment stay exactly as they are. Free opens the existing
    // paywall (the athlete just chose to send); Premium at its monthly limit gets the reset information the allowance area shows.
    // Unknown usage is not treated as exhausted: the server's own check below stays authoritative.
    if (!skipAllowanceCheck && !isPreviewMode && usage) {
      if (isFreeExhausted(usage)) {
        void openPaywallForPendingSend({ text: trimmed, image, requestId });
        return;
      }
      if (isPremiumExhausted(usage)) {
        setErrorText(formatPremiumExhaustedMessage(usage));
        return;
      }
    }

    // First-use consent gate (B.12) — checked before ANYTHING else in this function: before the
    // user's message is added to the transcript, before inputText/stagedImage are cleared, before
    // any network call. Developer Preview never reaches the real network layer at all (see the
    // isPreviewMode branch below), so it's exempt — gating a canned, clearly-labeled sample reply
    // would be pure friction with nothing real to disclose. A signed-out athlete (no session,
    // should be unreachable in practice) is let through to fail normally downstream rather than
    // gated on an account that doesn't exist.
    const athleteId = session?.user.id;
    if (!isPreviewMode && athleteId) {
      const agreed = await hasAgreedToSignalDisclosure(athleteId);
      if (!agreed) {
        setPendingSignalSend({ text: trimmed, image, requestId });
        setShowConsentSheet(true);
        return;
      }
    }

    followLatestRef.current = true;
    isSendingRef.current = true;
    setIsSending(true);
    setErrorText(null);
    setLastFailedAttempt(null);
    setMessages((current) => [...current, { id: `${Date.now()}-user`, role: 'user', text: trimmed, hadImage: !!image }]);
    setInputText('');
    setStagedImage(null);
    setThinkingStatus(THINKING_STATUSES[0]!);

    if (isPreviewMode) {
      // Never calls sendSignalMessage (lib/signal.ts) or appendSignalTurn/createSignalConversation
      // (lib/db/signal.ts) — a canned, clearly-labeled reply instead, so a tester who types into the
      // preview chat gets an honest response rather than a silent no-op or a real network call.
      setMessages((current) => [...current, { id: `${Date.now()}-assistant`, role: 'assistant', text: PREVIEW_FOLLOWUP_REPLY }]);
      isSendingRef.current = false;
      setIsSending(false);
      return;
    }

    let appliedReplyUsage = false;
    let gateRequest: { text: string; image: StagedImage | null; requestId: string } | null = null;
    try {
      const context = buildSignalContext(races.data, effectiveSeedRaceId);
      const history: SignalChatTurn[] = messages.map((message) => ({ role: message.role, text: message.text }));

      const result = await sendSignalMessage(
        context,
        history,
        trimmed,
        requestId,
        image ? { base64: image.base64, mediaType: image.mediaType } : undefined,
      );

      if (!result.available) {
        // `result.detail` (a safe, truncated backend diagnostic — see lib/signal.ts) is
        // deliberately not shown here: it was useful while chasing real device failures, but an
        // athlete-facing error should stay short and friendly, never expose implementation
        // details. It's still logged via console.warn in sendSignalMessage for developer use.
        if (result.reason === 'rate_limited') {
          // The server's own allowance check is authoritative, and it just said no. The question was not answered, so it leaves
          // the thread and the draft and attachment go back to the composer exactly as they were.
          setMessages((current) => (current.length > 0 && current[current.length - 1]?.role === 'user' ? current.slice(0, -1) : current));
          setInputText(trimmed);
          setStagedImage(image);
          // Which tier hit its limit comes from a fresh server read; only if that is unavailable does the app's own entitlement
          // decide, and it is never treated as exhausted-Premium on a guess.
          const fresh = await refreshUsage();
          if (fresh ? fresh.isPremium : isPremium) {
            setErrorText(fresh ? formatPremiumExhaustedMessage(fresh) : formatPremiumExhaustedMessage({ remaining: 0, cap: PREMIUM_MONTHLY_ASKS, isPremium: true, resetsAt: null }));
            return;
          }
          if (paywallInFlightRef.current) {
            // Already inside the paywall hand-off (the server has not yet recognized a just-completed purchase): never loop.
            setErrorText("Signal couldn't confirm your Premium access yet. Your question is saved, so try again in a moment.");
            return;
          }
          gateRequest = { text: trimmed, image, requestId };
          return;
        }
        // Every other failure reason (timeout, network_error, model_error, service_unavailable,
        // bad_request, forbidden, unauthorized) is recoverable via Retry — see retryLastMessage
        // below and its render. The rate_limited branch above is deliberately excluded: a capped
        // athlete retrying the identical question would just fail again identically, and it
        // already offers its own recovery (the paywall for free, the reset time for Premium).
        setErrorText(REASON_MESSAGES[result.reason]);
        setLastFailedAttempt({ text: trimmed, image, requestId });
        return;
      }
      setMessages((current) => [...current, { id: `${Date.now()}-assistant`, role: 'assistant', text: result.data.reply }]);
      applyReplyUsage({ remaining: result.data.remaining, cap: result.data.cap, isPremium: result.data.isPremium });
      appliedReplyUsage = true;

      // Persist this turn — lazily creates the conversation on the first successful exchange, so
      // an abandoned chat with no real reply never shows up in "Recent Signals". A failure here is
      // soft: the conversation itself already succeeded, only the save didn't, so it's logged, not
      // surfaced as a chat error.
      const athleteId = session?.user.id;
      if (athleteId) {
        try {
          let activeConversationId = conversationId;
          if (!activeConversationId) {
            const title = buildConversationTitle(seedRace, trimmed);
            const created = await createSignalConversation(athleteId, title, effectiveSeedRaceId);
            activeConversationId = created.id;
            setConversationId(created.id);
          }
          await appendSignalTurn(activeConversationId, trimmed, result.data.reply);
        } catch (err) {
          console.warn('[Signal] failed to persist conversation turn:', err);
        }
      }
    } finally {
      isSendingRef.current = false;
      setIsSending(false);
      // The send has settled (answered, failed, rate-limited, or ended by the paywall): confirm the allowance with the server.
      void refreshUsage(appliedReplyUsage);
      // The server refused a free athlete's send: hand the same question (same request id) to the paywall, now that this send is over.
      if (gateRequest) void openPaywallForPendingSend(gateRequest);
    }
  }

  /**
   * The hand-off from a send that needs Premium (a free balance confirmed or reported exhausted) to the existing RevenueCat paywall.
   * Nothing is added to the thread and the draft and attachment stay in the composer. After the paywall returns, entitlement AND the
   * server's usage are re-read; the pending question is sent exactly once, with its original request id, and only if the server now
   * confirms an available allowance (a purchase does not necessarily give 40 unused asks: the real monthly counter decides). If
   * the paywall was dismissed, usage is still exhausted, or usage cannot be confirmed, nothing is sent.
   */
  async function openPaywallForPendingSend(pending: { text: string; image: StagedImage | null; requestId: string }) {
    if (paywallInFlightRef.current) return;
    paywallInFlightRef.current = true;
    try {
      await presentPremiumPaywall();
      await refreshPremiumStatus();
      const fresh = await refreshUsage();
      if (!fresh) {
        setErrorText(REASON_MESSAGES.service_unavailable);
        return;
      }
      if (fresh.remaining > 0) await sendMessage(pending.text, pending.image, pending.requestId, true);
    } finally {
      paywallInFlightRef.current = false;
    }
  }

  /** Re-submits exactly the attempt that just failed (Task 1a) — removes the trailing user bubble
   *  first (the same pattern the paywall-purchase retry above already uses) so the retried question
   *  doesn't render twice, then re-sends through the ordinary sendMessage path. This is a fresh
   *  request like any other manually-typed one, not a special "resume" — see lib/signal.ts and
   *  supabase/functions/signal/index.ts's reserve/release accounting for why a genuinely failed
   *  first attempt never consumed an ask in the first place, so this isn't a double-charge. */
  function retryLastMessage() {
    if (!lastFailedAttempt) return;
    const { text, image, requestId } = lastFailedAttempt;
    setLastFailedAttempt(null);
    setErrorText(null);
    setMessages((current) => (current.length > 0 && current[current.length - 1]?.role === 'user' ? current.slice(0, -1) : current));
    void sendMessage(text, image, requestId);
  }

  /** "Agree and continue" — records consent for THIS account at the CURRENT disclosure version,
   *  then resumes the exact attempt the gate held (sendMessage re-checks consent at its top, which
   *  now passes, so this is a plain re-invocation, not a second code path). */
  async function handleConsentAgree() {
    const pending = pendingSignalSend;
    setShowConsentSheet(false);
    setPendingSignalSend(null);
    const athleteId = session?.user.id;
    if (athleteId) {
      await saveSignalConsent({ athleteId, version: SIGNAL_CONSENT_DISCLOSURE_VERSION, agreedAt: new Date().toISOString() });
    }
    if (pending) {
      void sendMessage(pending.text, pending.image, pending.requestId);
    }
  }

  /** "Not now" (or dismissing the sheet any other way) — nothing was ever added to the transcript
   *  and inputText/stagedImage were never touched, so the athlete's question is exactly where they
   *  left it; the rest of the app (every other tab/screen) was never blocked in the first place. */
  function handleConsentDecline() {
    setShowConsentSheet(false);
    setPendingSignalSend(null);
  }

  // The compact usage strip's "Upgrade" action (Build 10 polish) — a plain upsell entry point, not
  // the exhausted-allowance paywall path above (which is triggered by a real rate_limited
  // response). Presents the same RevenueCat-hosted paywall either way.
  async function handleUpgradePress() {
    if (isUpgrading) return;
    setIsUpgrading(true);
    await presentPremiumPaywall();
    // Every paywall return re-reads entitlement and the server's usage, so the allowance area reflects a purchase or restore.
    await refreshPremiumStatus();
    await refreshUsage();
    setIsUpgrading(false);
  }

  const headerTitle = seedRace ? seedRace.name : 'Ask Signal';

  return (
    <KeyboardAvoidingView
      style={styles.flex}
      behavior={Platform.OS === 'ios' ? 'padding' : undefined}
      keyboardVerticalOffset={90}>
      <Stack.Screen options={{ title: headerTitle }} />
      <View style={styles.screen}>
        {races.isLoading || isLoadingConversation ? (
          <LoadingSkeleton rows={4} />
        ) : races.isError ? (
          <ErrorState />
        ) : (
          <ScrollView
            ref={scrollRef}
            contentContainerStyle={styles.content}
            contentInsetAdjustmentBehavior="automatic"
            scrollEventThrottle={16}
            onScroll={(event) => {
              const { contentOffset, contentSize, layoutMeasurement } = event.nativeEvent;
              followLatestRef.current = isNearBottom({ contentOffsetY: contentOffset.y, contentHeight: contentSize.height, viewportHeight: layoutMeasurement.height });
            }}
            onContentSizeChange={() => {
              if (followLatestRef.current) scrollRef.current?.scrollToEnd({ animated: true });
            }}>
            {seedRace ? (
              <Text style={styles.seedNote}>
                Signal has your {seedRace.name} result and your full race history.
              </Text>
            ) : (
              <Text style={styles.seedNote}>Signal has your full race history.</Text>
            )}

            {messages.length > 0 ? (
              <View style={styles.messages}>
                {messages.map((message, index) => {
                  const topGap = messageTopGap(message.role, messages[index - 1]?.role);
                  if (message.role === 'user') {
                    return (
                      <View key={message.id} style={[styles.questionRow, { marginTop: topGap }]}>
                        <View
                          style={styles.questionBubble}
                          accessible
                          accessibilityLabel={`Your question${message.hadImage ? ', with a screenshot attached' : ''}. ${message.text}`}>
                          {message.hadImage ? (
                            <View style={styles.imageTagRow}>
                              <AppIcon name="camera-outline" size={13} color={palette.inkSecondary} />
                              <Text style={styles.imageTag}>Screenshot attached</Text>
                            </View>
                          ) : null}
                          <Text style={styles.questionText}>{message.text}</Text>
                        </View>
                      </View>
                    );
                  }
                  return (
                    <View key={message.id} style={[styles.answerBlock, { marginTop: topGap }]}>
                      <View style={styles.assistantLabelRow} accessible accessibilityRole="header" accessibilityLabel="Signal's answer">
                        <SignalMark color={palette.inkSecondary} size={11} />
                        <Text style={styles.assistantLabel}>{isPreviewMode ? 'Signal sample (Developer Preview)' : 'Signal'}</Text>
                      </View>
                      <View style={styles.assistantParagraphs}>
                        {splitParagraphs(message.text).map((paragraph, paragraphIndex) => (
                          <Text key={paragraphIndex} style={styles.answerText}>
                            {paragraph}
                          </Text>
                        ))}
                      </View>
                    </View>
                  );
                })}
                {isSending ? (
                  <View style={styles.thinkingRow}>
                    <SignalMark color={palette.inkSecondary} size={12} />
                    <Text style={styles.thinkingText}>{thinkingStatus}</Text>
                  </View>
                ) : null}
              </View>
            ) : null}

            {messages.length === 0 && !isSending && suggestions.length > 0 ? (
              <View style={styles.suggestionRow}>
                <HairlineRule color={palette.hairline} />
                {suggestions.map((suggestion, index) => (
                  <View key={suggestion}>
                    <Pressable
                      onPress={() => sendMessage(suggestion)}
                      accessibilityRole="button"
                      accessibilityLabel={suggestion}
                      style={styles.suggestionChip}>
                      <Text style={styles.suggestionLabel}>{suggestion}</Text>
                      <AppIcon name="chevron-right" size={17} color={palette.inkSecondary} />
                    </Pressable>
                    {index < suggestions.length - 1 ? <HairlineRule color={palette.hairline} /> : null}
                  </View>
                ))}
              </View>
            ) : null}

            {errorText ? (
              <View style={styles.errorRow}>
                <Text style={styles.errorText}>{errorText}</Text>
                {lastFailedAttempt ? (
                  <Pressable
                    onPress={retryLastMessage}
                    accessibilityRole="button"
                    accessibilityLabel="Retry"
                    style={styles.retryButton}>
                    <Text style={styles.retryButtonLabel}>Retry</Text>
                  </Pressable>
                ) : null}
              </View>
            ) : null}

            {messages.length === 0 && !isSending && !stagedImage ? (
              <View style={styles.attachHintRow}>
                <AppIcon name="camera-outline" size={13} color={palette.inkSecondary} />
                <Text style={styles.attachHintText}>
                  Add a training or race screenshot as evidence — a Garmin, Strava, or TrainingPeaks screenshot works
                  well. It&rsquo;s just a picture of what you already have open, not a live connection to those apps.
                </Text>
              </View>
            ) : null}
          </ScrollView>
        )}

        {stagedImage ? (
          <View style={styles.stagedImageRow}>
            <Image source={{ uri: stagedImage.previewUri }} style={styles.stagedImageThumb} />
            <Text style={styles.stagedImageLabel}>Screenshot ready to send</Text>
            <Pressable
              onPress={() => setStagedImage(null)}
              accessibilityRole="button"
              accessibilityLabel="Remove screenshot"
              hitSlop={8}
              style={styles.stagedImageRemove}>
              <AppIcon name="close" size={16} color={palette.inkSecondary} />
            </Pressable>
          </View>
        ) : null}

        {starterOffer ? (
          <View style={styles.starterOffer} testID="starter-offer">
            <Text style={styles.starterText}>You already have a draft. Add the suggested starter after it?</Text>
            <Text style={styles.starterQuote}>{`\u201C${starterOffer}\u201D`}</Text>
            <View style={styles.starterButtons}>
              <Pressable
                onPress={() => {
                  setInputText((current) => appendStarter(current, starterOffer));
                  setStarterOffer(null);
                  requestFocus();
                }}
                accessibilityRole="button"
                accessibilityLabel="Add starter"
                style={styles.starterButton}>
                <Text style={styles.starterButtonLabel}>Add starter</Text>
              </Pressable>
              <Pressable onPress={() => setStarterOffer(null)} accessibilityRole="button" accessibilityLabel="Keep my draft" style={styles.starterButton}>
                <Text style={styles.starterSecondaryLabel}>Keep my draft</Text>
              </Pressable>
            </View>
          </View>
        ) : null}

        {Constants.expoConfig?.extra?.appVariant === 'development' && focusStatus.attempts > 0 ? (
          <Text style={styles.focusDiagnostic} testID="focus-diagnostic">
            {`Keyboard focus (development): ${focusStatus.focused === true ? 'focused' : focusStatus.focused === false ? 'NOT focused' : 'trying'} after ${focusStatus.attempts} attempt${focusStatus.attempts === 1 ? '' : 's'}, app ${AppState.currentState}`}
          </Text>
        ) : null}

        {/* The allowance area: compact, two lines, server-confirmed counts only (see SignalAllowance). */}
        <SignalAllowance usage={usage} onExplorePremium={handleUpgradePress} />

        <View style={styles.inputBar}>
          <Pressable
            onPress={pickImage}
            accessibilityRole="button"
            accessibilityLabel="Attach a screenshot"
            style={styles.attachButton}>
            <AppIcon name="camera-outline" size={22} color={palette.signalBlue} />
          </Pressable>
          <TextInput
            ref={inputRef}
            value={inputText}
            onChangeText={setInputText}
            placeholder="Ask Signal about your races…"
            placeholderTextColor={palette.inkSecondary}
            style={styles.input}
            accessibilityLabel="Message"
            multiline
            // The send button is the ONLY send action (V1 device-test requirement) — keyboard
            // Return must only ever insert a newline. blurOnSubmit={false} keeps the keyboard from
            // dismissing on Return (the multiline default, made explicit here rather than relied
            // on), returnKeyType="default" keeps the key labeled/behaving like a plain return
            // rather than a "Send"/"Go" key, and onSubmitEditing is an explicit no-op so no future
            // change can accidentally wire Return to sendMessage.
            blurOnSubmit={false}
            returnKeyType="default"
            onSubmitEditing={() => {}}
          />
          <Pressable
            onPress={() => sendMessage(inputText)}
            disabled={inputText.trim().length === 0 || isSending}
            accessibilityRole="button"
            accessibilityLabel="Send"
            style={[styles.sendButton, (inputText.trim().length === 0 || isSending) && styles.sendButtonDisabled]}>
            <AppIcon name="arrow-up" size={20} color={palette.onSignalBlue} />
          </Pressable>
        </View>
      </View>
      <SignalConsentSheet visible={showConsentSheet} onAgree={handleConsentAgree} onDecline={handleConsentDecline} />
    </KeyboardAvoidingView>
  );
}

interface Styles {
  flex: ViewStyle;
  screen: ViewStyle;
  content: ViewStyle;
  seedNote: TextStyle;
  messages: ViewStyle;
  questionRow: ViewStyle;
  questionBubble: ViewStyle;
  questionText: TextStyle;
  answerBlock: ViewStyle;
  answerText: TextStyle;
  assistantLabelRow: ViewStyle;
  assistantLabel: TextStyle;
  assistantParagraphs: ViewStyle;
  imageTagRow: ViewStyle;
  imageTag: TextStyle;
  thinkingRow: ViewStyle;
  thinkingText: TextStyle;
  suggestionRow: ViewStyle;
  suggestionChip: ViewStyle;
  suggestionLabel: TextStyle;
  errorRow: ViewStyle;
  errorText: TextStyle;
  retryButton: ViewStyle;
  retryButtonLabel: TextStyle;
  attachHintRow: ViewStyle;
  attachHintText: TextStyle;
  focusDiagnostic: TextStyle;
  starterOffer: ViewStyle;
  starterText: TextStyle;
  starterQuote: TextStyle;
  starterButtons: ViewStyle;
  starterButton: ViewStyle;
  starterButtonLabel: TextStyle;
  starterSecondaryLabel: TextStyle;
  stagedImageRow: ViewStyle;
  stagedImageThumb: ImageStyle;
  stagedImageLabel: TextStyle;
  stagedImageRemove: ViewStyle;
  inputBar: ViewStyle;
  attachButton: ViewStyle;
  input: TextStyle;
  sendButton: ViewStyle;
  sendButtonDisabled: ViewStyle;
}

function createStyles(palette: BrandPalette): Styles {
  return StyleSheet.create({
    flex: {
      flex: 1,
    },
    screen: {
      flex: 1,
      backgroundColor: palette.canvas,
    },
    content: {
      padding: spacing.lg,
      gap: spacing.md,
    },
    seedNote: {
      fontSize: 13,
      color: palette.inkSecondary,
    },
    messages: {},
    // Questions: right-aligned, muted blue-grey bubble (the brand's signal blue at low strength over the canvas, so it
    // follows light and dark), at most 85% of the width, 16pt regular text, 14pt padding, 16pt corners. No fixed height,
    // so larger text sizes grow the bubble rather than clip it.
    questionRow: {
      alignItems: 'flex-end',
    },
    questionBubble: {
      maxWidth: QUESTION_BUBBLE_MAX_WIDTH,
      padding: 14,
      borderRadius: 16,
      gap: 6,
      backgroundColor: withAlpha(palette.signalBlue, palette.statusBarStyle === 'dark' ? 0.12 : 0.22),
    },
    questionText: {
      fontSize: 16,
      fontWeight: '400',
      color: palette.ink,
    },
    // Answers: left-aligned on the canvas itself, no card, no rule. The mark and a small SIGNAL label sit above every answer.
    answerBlock: {
      alignItems: 'flex-start',
      gap: 8,
    },
    answerText: {
      fontSize: 17,
      fontWeight: '400',
      lineHeight: 25,
      color: palette.ink,
    },
    assistantLabelRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    // Small SIGNAL label above every answer: letter-spaced caps in the quiet secondary ink, next to the mark.
    assistantLabel: {
      fontSize: 11,
      fontWeight: '700',
      letterSpacing: 1,
      textTransform: 'uppercase',
      color: palette.inkSecondary,
    },
    // Paragraph breaks in the reply text itself, with no weight difference between paragraphs.
    assistantParagraphs: {
      alignSelf: 'stretch',
      gap: spacing.md,
    },
    imageTagRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
    },
    imageTag: {
      fontSize: 12,
      color: palette.inkSecondary,
    },
    thinkingRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingVertical: spacing.xs,
    },
    thinkingText: {
      fontSize: 13,
      fontStyle: 'italic',
      color: palette.inkSecondary,
    },
    suggestionRow: {
      gap: 0,
    },
    // Editorial row, not a pill — matches the Signal tab landing screen's "Things worth asking"
    // treatment: question text, subtle chevron, hairline separators between rows.
    suggestionChip: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: spacing.sm,
      minHeight: 44,
      paddingVertical: spacing.sm,
    },
    suggestionLabel: {
      flex: 1,
      fontSize: 14,
      fontWeight: '500',
      color: palette.ink,
    },
    errorRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: spacing.sm,
    },
    errorText: {
      flex: 1,
      fontSize: 13,
      color: palette.danger,
    },
    // Retry action for a failed/timed-out question (Task 1a) — a small, clearly-labeled recovery
    // action right next to the error, never a dead end that forces retyping the question.
    retryButton: {
      minHeight: minTouchSize,
      paddingHorizontal: spacing.sm,
      alignItems: 'center',
      justifyContent: 'center',
    },
    retryButtonLabel: {
      fontSize: 13,
      fontWeight: '700',
      color: palette.signalBlue,
      textDecorationLine: 'underline',
    },
    // Screenshot-attachment discoverability (Task 3.3) — quiet, one-time-per-empty-chat helper copy
    // near the attach control, phrased so it never implies a live/direct Garmin/Strava/TrainingPeaks
    // integration (there isn't one — it's just an ordinary screenshot, same as any other image).
    attachHintRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 6,
    },
    attachHintText: {
      flex: 1,
      fontSize: 12,
      lineHeight: 17,
      color: palette.inkSecondary,
    },
    focusDiagnostic: { marginHorizontal: spacing.lg, fontSize: 11, color: palette.inkSecondary },
    starterOffer: {
      marginHorizontal: spacing.lg,
      marginBottom: spacing.xs,
      padding: spacing.md,
      gap: spacing.xs,
      borderRadius: 12,
      backgroundColor: withAlpha(palette.signalBlue, 0.08),
    },
    starterText: { fontSize: 13, color: palette.inkSecondary },
    starterQuote: { fontSize: 15, color: palette.ink },
    starterButtons: { flexDirection: 'row', gap: spacing.lg },
    starterButton: { minHeight: minTouchSize, justifyContent: 'center' },
    starterButtonLabel: { fontSize: 14, fontWeight: '700', color: palette.signalBlue },
    starterSecondaryLabel: { fontSize: 14, fontWeight: '600', color: palette.inkSecondary },
    stagedImageRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.sm,
      paddingHorizontal: spacing.md,
      paddingTop: spacing.sm,
      backgroundColor: palette.canvas,
    },
    stagedImageThumb: {
      width: 36,
      height: 36,
      borderRadius: 8,
    },
    stagedImageLabel: {
      fontSize: 13,
      color: palette.inkSecondary,
      flex: 1,
    },
    stagedImageRemove: {
      minWidth: 32,
      minHeight: 32,
      alignItems: 'center',
      justifyContent: 'center',
    },
    inputBar: {
      flexDirection: 'row',
      alignItems: 'flex-end',
      gap: spacing.sm,
      padding: spacing.md,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: palette.hairline,
      backgroundColor: palette.canvas,
    },
    attachButton: {
      minWidth: minTouchSize,
      minHeight: minTouchSize,
      alignItems: 'center',
      justifyContent: 'center',
    },
    input: {
      flex: 1,
      minHeight: minTouchSize,
      maxHeight: 100,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: palette.hairline,
      borderRadius: 20,
      paddingHorizontal: spacing.md,
      paddingVertical: spacing.sm,
      color: palette.ink,
    },
    sendButton: {
      width: minTouchSize,
      height: minTouchSize,
      borderRadius: minTouchSize / 2,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: palette.signalBlue,
    },
    sendButtonDisabled: {
      opacity: 0.4,
    },
  });
}
